import { Customer, Deal, Activity, User } from "@/types";

export const sampleUsers: User[] = [
  { id: "u1", name: "田中 太郎", email: "tanaka@example.com", role: "admin" },
  { id: "u2", name: "鈴木 花子", email: "suzuki@example.com", role: "manager" },
  { id: "u3", name: "佐藤 次郎", email: "sato@example.com", role: "sales" },
  { id: "u4", name: "山田 三郎", email: "yamada@example.com", role: "sales" },
  { id: "u5", name: "伊藤 良子", email: "ito@example.com", role: "sales" },
];

export const sampleCustomers: Customer[] = [
  {
    id: "c1", name: "山本 健一", company: "株式会社テックソリューション",
    email: "yamamoto@techsolution.co.jp", phone: "03-1234-5678",
    industry: "IT", status: "active", address: "東京都渋谷区神南1-1-1",
    website: "https://techsolution.co.jp", assignedTo: "u3",
    notes: "大手IT企業。意思決定が速い。クラウド移行に積極的。",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face",
    createdAt: new Date("2024-01-10").toISOString(), updatedAt: new Date("2024-03-15").toISOString(),
  },
  {
    id: "c2", name: "中村 美咲", company: "フィナンシャルグループ株式会社",
    email: "nakamura@financial.co.jp", phone: "03-2345-6789",
    industry: "finance", status: "active", address: "東京都千代田区丸の内2-2-2",
    website: "https://financial.co.jp", assignedTo: "u3",
    notes: "金融系。コンプライアンス重視。決裁に時間がかかる傾向あり。",
    avatar: "https://images.unsplash.com/photo-1494790108755-2616b612b77c?w=100&h=100&fit=crop&crop=face",
    createdAt: new Date("2024-02-05").toISOString(), updatedAt: new Date("2024-03-20").toISOString(),
  },
  {
    id: "c3", name: "伊藤 直樹", company: "製造工業株式会社",
    email: "ito@seizou.co.jp", phone: "052-3456-7890",
    industry: "manufacturing", status: "prospect", address: "愛知県名古屋市中区錦3-3-3",
    website: "https://seizou.co.jp", assignedTo: "u4",
    notes: "製造業。DX推進中。IoT活用に関心が高い。",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face",
    createdAt: new Date("2024-02-20").toISOString(), updatedAt: new Date("2024-03-10").toISOString(),
  },
  {
    id: "c4", name: "高橋 恵子", company: "小売チェーン株式会社",
    email: "takahashi@retail.co.jp", phone: "06-4567-8901",
    industry: "retail", status: "inactive", address: "大阪府大阪市北区梅田4-4-4",
    website: "https://retail.co.jp", assignedTo: "u4",
    notes: "小売業。予算が限られているが将来的な拡大を検討中。",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face",
    createdAt: new Date("2024-01-25").toISOString(), updatedAt: new Date("2024-02-28").toISOString(),
  },
  {
    id: "c5", name: "松本 幸雄", company: "ヘルスケアサービス株式会社",
    email: "matsumoto@healthcare.co.jp", phone: "011-5678-9012",
    industry: "healthcare", status: "active", address: "北海道札幌市中央区大通西5-5-5",
    website: "https://healthcare.co.jp", assignedTo: "u3",
    notes: "医療系。セキュリティ要件が厳しい。個人情報保護に敏感。",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face",
    createdAt: new Date("2024-03-01").toISOString(), updatedAt: new Date("2024-03-25").toISOString(),
  },
  {
    id: "c6", name: "渡辺 真理", company: "教育サービス株式会社",
    email: "watanabe@education.co.jp", phone: "03-6789-0123",
    industry: "education", status: "active", address: "東京都新宿区西新宿6-6-6",
    website: "https://education.co.jp", assignedTo: "u5",
    notes: "教育系スタートアップ。成長中。オンライン学習プラットフォームを展開。",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&h=100&fit=crop&crop=face",
    createdAt: new Date("2024-01-15").toISOString(), updatedAt: new Date("2024-03-18").toISOString(),
  },
  {
    id: "c7", name: "木村 誠", company: "建設コンサルタント株式会社",
    email: "kimura@construction.co.jp", phone: "06-7890-1234",
    industry: "other", status: "prospect", address: "大阪府大阪市中央区本町7-7-7",
    website: "https://construction.co.jp", assignedTo: "u5",
    notes: "建設業界のDX推進担当。現場管理システムに興味あり。",
    avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=100&h=100&fit=crop&crop=face",
    createdAt: new Date("2024-02-10").toISOString(), updatedAt: new Date("2024-03-05").toISOString(),
  },
  {
    id: "c8", name: "林 由美子", company: "物流ネットワーク株式会社",
    email: "hayashi@logistics.co.jp", phone: "045-8901-2345",
    industry: "other", status: "active", address: "神奈川県横浜市西区みなとみらい8-8-8",
    website: "https://logistics.co.jp", assignedTo: "u3",
    notes: "物流大手。倉庫管理システムの刷新を検討中。",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&h=100&fit=crop&crop=face",
    createdAt: new Date("2024-01-20").toISOString(), updatedAt: new Date("2024-03-22").toISOString(),
  },
  {
    id: "c9", name: "加藤 龍一", company: "エナジーテック株式会社",
    email: "kato@energytech.co.jp", phone: "092-9012-3456",
    industry: "IT", status: "prospect", address: "福岡県福岡市博多区博多駅前9-9-9",
    website: "https://energytech.co.jp", assignedTo: "u4",
    notes: "エネルギー×ITの新興企業。再生可能エネルギー管理に注力。",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100&h=100&fit=crop&crop=face",
    createdAt: new Date("2024-03-05").toISOString(), updatedAt: new Date("2024-03-28").toISOString(),
  },
  {
    id: "c10", name: "岡田 夏希", company: "メディアクリエイト株式会社",
    email: "okada@mediacreate.co.jp", phone: "03-0123-4567",
    industry: "IT", status: "churned", address: "東京都港区六本木10-10-10",
    website: "https://mediacreate.co.jp", assignedTo: "u5",
    notes: "デジタルメディア企業。予算削減により一時休止。来期再開の可能性あり。",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&h=100&fit=crop&crop=face",
    createdAt: new Date("2023-11-01").toISOString(), updatedAt: new Date("2024-02-15").toISOString(),
  },
  {
    id: "c11", name: "西村 浩二", company: "アグリテック株式会社",
    email: "nishimura@agritech.co.jp", phone: "086-1234-5678",
    industry: "other", status: "active", address: "岡山県岡山市北区駅前11-11-11",
    website: "https://agritech.co.jp", assignedTo: "u4",
    notes: "農業DX推進企業。スマート農業に特化。補助金活用に積極的。",
    avatar: "https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=100&h=100&fit=crop&crop=face",
    createdAt: new Date("2024-02-25").toISOString(), updatedAt: new Date("2024-03-20").toISOString(),
  },
  {
    id: "c12", name: "藤田 彩", company: "ウェルネスライフ株式会社",
    email: "fujita@wellness.co.jp", phone: "03-2345-6789",
    industry: "healthcare", status: "active", address: "東京都目黒区中目黒12-12-12",
    website: "https://wellness.co.jp", assignedTo: "u5",
    notes: "ヘルステック。ウェアラブルデバイスと連携したサービスを展開。",
    avatar: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=100&h=100&fit=crop&crop=face",
    createdAt: new Date("2024-01-08").toISOString(), updatedAt: new Date("2024-03-15").toISOString(),
  },
];

export const sampleDeals: Deal[] = [
  // ── 進行中商談 ──────────────────────────────────────────
  {
    id: "d1", title: "クラウド移行プロジェクト",
    customerId: "c1", customerName: "株式会社テックソリューション",
    amount: 5000000, stage: "proposal", probability: 60,
    expectedCloseDate: new Date("2026-05-30").toISOString(),
    assignedTo: "u3", description: "オンプレからAWSへの完全移行。3フェーズに分けて実施予定。",
    tags: ["クラウド", "AWS", "インフラ"],
    createdAt: new Date("2026-02-01").toISOString(), updatedAt: new Date("2026-03-01").toISOString(),
  },
  {
    id: "d2", title: "金融システムリプレイス",
    customerId: "c2", customerName: "フィナンシャルグループ株式会社",
    amount: 12000000, stage: "negotiation", probability: 75,
    expectedCloseDate: new Date("2026-06-30").toISOString(),
    assignedTo: "u3", description: "勘定系システムの全面刷新。セキュリティ強化が最優先。",
    tags: ["金融", "基幹システム", "セキュリティ"],
    createdAt: new Date("2026-01-15").toISOString(), updatedAt: new Date("2026-03-01").toISOString(),
  },
  {
    id: "d3", title: "製造ライン自動化システム",
    customerId: "c3", customerName: "製造工業株式会社",
    amount: 8000000, stage: "qualified", probability: 40,
    expectedCloseDate: new Date("2026-07-31").toISOString(),
    assignedTo: "u4", description: "IoTセンサーと連携した生産管理システム。リアルタイム監視機能付き。",
    tags: ["IoT", "製造", "自動化"],
    createdAt: new Date("2026-02-01").toISOString(), updatedAt: new Date("2026-03-01").toISOString(),
  },
  {
    id: "d4", title: "ECサイトリニューアル",
    customerId: "c4", customerName: "小売チェーン株式会社",
    amount: 3000000, stage: "lead", probability: 20,
    expectedCloseDate: new Date("2026-08-31").toISOString(),
    assignedTo: "u4", description: "既存ECの全面リニューアル。モバイルファースト対応。",
    tags: ["EC", "Web", "モバイル"],
    createdAt: new Date("2026-02-10").toISOString(), updatedAt: new Date("2026-02-10").toISOString(),
  },
  {
    id: "d6", title: "LMS導入プロジェクト",
    customerId: "c6", customerName: "教育サービス株式会社",
    amount: 4200000, stage: "proposal", probability: 55,
    expectedCloseDate: new Date("2026-06-15").toISOString(),
    assignedTo: "u5", description: "学習管理システムの新規導入。動画配信機能・テスト機能が必須。",
    tags: ["教育", "LMS", "SaaS"],
    createdAt: new Date("2026-01-15").toISOString(), updatedAt: new Date("2026-02-19").toISOString(),
  },
  {
    id: "d7", title: "現場管理アプリ開発",
    customerId: "c7", customerName: "建設コンサルタント株式会社",
    amount: 7800000, stage: "qualified", probability: 35,
    expectedCloseDate: new Date("2026-09-30").toISOString(),
    assignedTo: "u5", description: "建設現場向けモバイルアプリ。図面管理・進捗報告機能を実装。",
    tags: ["建設", "モバイル", "現場管理"],
    createdAt: new Date("2026-01-28").toISOString(), updatedAt: new Date("2026-02-12").toISOString(),
  },
  {
    id: "d8", title: "倉庫管理システム刷新",
    customerId: "c8", customerName: "物流ネットワーク株式会社",
    amount: 15000000, stage: "negotiation", probability: 80,
    expectedCloseDate: new Date("2026-07-15").toISOString(),
    assignedTo: "u3", description: "WMSの全面刷新。バーコード・RFID連携対応。自動化倉庫との連携も視野。",
    tags: ["物流", "WMS", "RFID", "自動化"],
    createdAt: new Date("2026-01-25").toISOString(), updatedAt: new Date("2026-03-01").toISOString(),
  },
  {
    id: "d9", title: "エネルギー管理プラットフォーム",
    customerId: "c9", customerName: "エナジーテック株式会社",
    amount: 9500000, stage: "lead", probability: 25,
    expectedCloseDate: new Date("2026-10-31").toISOString(),
    assignedTo: "u4", description: "再生可能エネルギーのリアルタイム管理プラットフォーム。",
    tags: ["エネルギー", "IoT", "プラットフォーム"],
    createdAt: new Date("2026-02-08").toISOString(), updatedAt: new Date("2026-02-08").toISOString(),
  },
  {
    id: "d10", title: "スマート農業管理システム",
    customerId: "c11", customerName: "アグリテック株式会社",
    amount: 3800000, stage: "proposal", probability: 50,
    expectedCloseDate: new Date("2026-06-30").toISOString(),
    assignedTo: "u4", description: "センサーデータを活用した圃場管理システム。気象データ連携も含む。",
    tags: ["農業", "IoT", "センサー"],
    createdAt: new Date("2026-02-01").toISOString(), updatedAt: new Date("2026-02-21").toISOString(),
  },
  {
    id: "d15", title: "データ分析基盤構築",
    customerId: "c6", customerName: "教育サービス株式会社",
    amount: 3200000, stage: "negotiation", probability: 70,
    expectedCloseDate: new Date("2026-05-31").toISOString(),
    assignedTo: "u5", description: "学習データの収集・分析基盤。BIツール連携でKPI可視化。",
    tags: ["データ分析", "BI", "教育"],
    createdAt: new Date("2026-02-20").toISOString(), updatedAt: new Date("2026-03-01").toISOString(),
  },

  // ── 受注済み（closed_won）直近12ヶ月分 ──────────────────
  {
    id: "d16", title: "基幹システムAPI連携",
    customerId: "c1", customerName: "株式会社テックソリューション",
    amount: 4800000, stage: "closed_won", probability: 100,
    expectedCloseDate: new Date("2025-04-30").toISOString(),
    assignedTo: "u3", description: "社内基幹システムとSalesforce APIの連携開発。",
    tags: ["API", "連携", "基幹"],
    createdAt: new Date("2025-03-01").toISOString(), updatedAt: new Date("2025-04-30").toISOString(),
  },
  {
    id: "d17", title: "社内ポータルリニューアル",
    customerId: "c6", customerName: "教育サービス株式会社",
    amount: 3500000, stage: "closed_won", probability: 100,
    expectedCloseDate: new Date("2025-05-31").toISOString(),
    assignedTo: "u5", description: "社内イントラネットの全面リニューアル。",
    tags: ["Web", "社内システム"],
    createdAt: new Date("2025-04-01").toISOString(), updatedAt: new Date("2025-05-31").toISOString(),
  },
  {
    id: "d18", title: "物流追跡システム開発",
    customerId: "c8", customerName: "物流ネットワーク株式会社",
    amount: 7200000, stage: "closed_won", probability: 100,
    expectedCloseDate: new Date("2025-06-30").toISOString(),
    assignedTo: "u3", description: "リアルタイム荷物追跡システムの新規開発。",
    tags: ["物流", "リアルタイム", "追跡"],
    createdAt: new Date("2025-05-01").toISOString(), updatedAt: new Date("2025-06-30").toISOString(),
  },
  {
    id: "d19", title: "採用管理システム導入",
    customerId: "c11", customerName: "アグリテック株式会社",
    amount: 2900000, stage: "closed_won", probability: 100,
    expectedCloseDate: new Date("2025-07-31").toISOString(),
    assignedTo: "u4", description: "採用フロー全体をデジタル化。面接管理・評価シート機能付き。",
    tags: ["HR", "採用", "DX"],
    createdAt: new Date("2025-06-01").toISOString(), updatedAt: new Date("2025-07-31").toISOString(),
  },
  {
    id: "d5", title: "医療記録電子化",
    customerId: "c5", customerName: "ヘルスケアサービス株式会社",
    amount: 6500000, stage: "closed_won", probability: 100,
    expectedCloseDate: new Date("2025-08-31").toISOString(),
    assignedTo: "u3", description: "紙カルテの完全電子化。HIPAA準拠のセキュリティ対応。",
    tags: ["医療", "電子化", "セキュリティ"],
    createdAt: new Date("2025-07-01").toISOString(), updatedAt: new Date("2025-08-31").toISOString(),
  },
  {
    id: "d20", title: "予防保全AIシステム",
    customerId: "c3", customerName: "製造工業株式会社",
    amount: 9800000, stage: "closed_won", probability: 100,
    expectedCloseDate: new Date("2025-09-30").toISOString(),
    assignedTo: "u4", description: "機械の故障予測AIシステム。センサーデータを機械学習で分析。",
    tags: ["AI", "製造", "予防保全"],
    createdAt: new Date("2025-07-01").toISOString(), updatedAt: new Date("2025-09-30").toISOString(),
  },
  {
    id: "d11", title: "健康管理アプリ開発",
    customerId: "c12", customerName: "ウェルネスライフ株式会社",
    amount: 5500000, stage: "closed_won", probability: 100,
    expectedCloseDate: new Date("2025-10-31").toISOString(),
    assignedTo: "u5", description: "ウェアラブル連携の個人健康管理アプリ。Apple Health・Google Fit対応。",
    tags: ["ヘルスケア", "モバイル", "API連携"],
    createdAt: new Date("2025-09-01").toISOString(), updatedAt: new Date("2025-10-31").toISOString(),
  },
  {
    id: "d21", title: "決済システム刷新",
    customerId: "c2", customerName: "フィナンシャルグループ株式会社",
    amount: 11000000, stage: "closed_won", probability: 100,
    expectedCloseDate: new Date("2025-11-30").toISOString(),
    assignedTo: "u3", description: "オンライン決済基盤の全面刷新。PCI DSS準拠対応。",
    tags: ["金融", "決済", "セキュリティ"],
    createdAt: new Date("2025-09-01").toISOString(), updatedAt: new Date("2025-11-30").toISOString(),
  },
  {
    id: "d12", title: "セキュリティ監査システム",
    customerId: "c1", customerName: "株式会社テックソリューション",
    amount: 2800000, stage: "closed_won", probability: 100,
    expectedCloseDate: new Date("2025-12-31").toISOString(),
    assignedTo: "u3", description: "社内セキュリティの自動監査ツール。脆弱性スキャン機能付き。",
    tags: ["セキュリティ", "監査", "自動化"],
    createdAt: new Date("2025-11-01").toISOString(), updatedAt: new Date("2025-12-31").toISOString(),
  },
  {
    id: "d14", title: "顧客ポータルサイト構築",
    customerId: "c2", customerName: "フィナンシャルグループ株式会社",
    amount: 6000000, stage: "closed_won", probability: 100,
    expectedCloseDate: new Date("2026-01-31").toISOString(),
    assignedTo: "u3", description: "法人顧客向けセルフサービスポータル。契約・請求管理機能付き。",
    tags: ["金融", "ポータル", "Web"],
    createdAt: new Date("2025-12-01").toISOString(), updatedAt: new Date("2026-01-31").toISOString(),
  },
  {
    id: "d22", title: "健康診断管理プラットフォーム",
    customerId: "c12", customerName: "ウェルネスライフ株式会社",
    amount: 5100000, stage: "closed_won", probability: 100,
    expectedCloseDate: new Date("2026-02-28").toISOString(),
    assignedTo: "u5", description: "企業向け健康診断結果の一元管理プラットフォーム。",
    tags: ["医療", "健康管理", "SaaS"],
    createdAt: new Date("2025-12-01").toISOString(), updatedAt: new Date("2026-02-28").toISOString(),
  },
  {
    id: "d23", title: "スマート店舗管理システム",
    customerId: "c4", customerName: "小売チェーン株式会社",
    amount: 6300000, stage: "closed_won", probability: 100,
    expectedCloseDate: new Date("2026-03-05").toISOString(),
    assignedTo: "u4", description: "店舗の在庫・売上・人員をリアルタイム管理するシステム。",
    tags: ["小売", "店舗管理", "リアルタイム"],
    createdAt: new Date("2026-01-10").toISOString(), updatedAt: new Date("2026-03-05").toISOString(),
  },

  // ── 失注 ─────────────────────────────────────────────────
  {
    id: "d13", title: "HR管理システム導入",
    customerId: "c8", customerName: "物流ネットワーク株式会社",
    amount: 4500000, stage: "closed_lost", probability: 0,
    expectedCloseDate: new Date("2025-10-31").toISOString(),
    assignedTo: "u3", description: "人事・給与管理システム。競合他社に敗れ失注。価格が主な敗因。",
    tags: ["HR", "人事", "給与"],
    createdAt: new Date("2025-08-01").toISOString(), updatedAt: new Date("2025-10-31").toISOString(),
  },
];

export const sampleActivities: Activity[] = [
  {
    id: "a1", type: "meeting", subject: "初回提案ミーティング",
    description: "クラウド移行の初回提案。先方IT部長・CTO同席。概算見積もりを提示し好感触。次回詳細要件ヒアリングを設定。",
    customerId: "c1", customerName: "株式会社テックソリューション",
    dealId: "d1", dealTitle: "クラウド移行プロジェクト",
    assignedTo: "u3", scheduledAt: new Date("2026-02-20T10:00:00").toISOString(),
    completedAt: new Date("2026-02-20T11:30:00").toISOString(), completed: true,
    createdAt: new Date("2026-02-20").toISOString(),
  },
  {
    id: "a2", type: "call", subject: "価格交渉の電話",
    description: "金額について再協議。5%ディスカウント提示。先方担当者は前向きだが役員承認が必要とのこと。",
    customerId: "c2", customerName: "フィナンシャルグループ株式会社",
    dealId: "d2", dealTitle: "金融システムリプレイス",
    assignedTo: "u3", scheduledAt: new Date("2026-02-22T14:00:00").toISOString(),
    completedAt: new Date("2026-02-22T14:45:00").toISOString(), completed: true,
    createdAt: new Date("2026-02-22").toISOString(),
  },
  {
    id: "a3", type: "email", subject: "提案書送付",
    description: "製造ライン自動化の提案書をメールで送付。ROI試算資料も添付。1週間以内に返答をお願いした。",
    customerId: "c3", customerName: "製造工業株式会社",
    dealId: "d3", dealTitle: "製造ライン自動化システム",
    assignedTo: "u4", scheduledAt: new Date("2026-02-25T09:00:00").toISOString(),
    completed: false, createdAt: new Date("2026-02-25").toISOString(),
  },
  {
    id: "a4", type: "task", subject: "ROI試算資料作成",
    description: "ECリニューアルのROI試算資料を作成する。競合比較表も含める。",
    customerId: "c4", customerName: "小売チェーン株式会社",
    assignedTo: "u4", scheduledAt: new Date("2026-03-10T17:00:00").toISOString(),
    completed: false, createdAt: new Date("2026-03-01").toISOString(),
  },
  {
    id: "a5", type: "note", subject: "契約締結完了",
    description: "医療記録電子化の契約締結。キックオフは来月4/10予定。担当PMを紹介してもらう。",
    customerId: "c5", customerName: "ヘルスケアサービス株式会社",
    dealId: "d5", dealTitle: "医療記録電子化",
    assignedTo: "u3", scheduledAt: new Date("2025-08-28T15:00:00").toISOString(),
    completedAt: new Date("2025-08-28T15:30:00").toISOString(), completed: true,
    createdAt: new Date("2025-08-28").toISOString(),
  },
  {
    id: "a6", type: "meeting", subject: "LMSデモ実施",
    description: "学習管理システムのデモを実施。動画配信機能と進捗管理に高評価。価格感についての確認が必要。",
    customerId: "c6", customerName: "教育サービス株式会社",
    dealId: "d6", dealTitle: "LMS導入プロジェクト",
    assignedTo: "u5", scheduledAt: new Date("2026-02-19T13:00:00").toISOString(),
    completedAt: new Date("2026-02-19T14:30:00").toISOString(), completed: true,
    createdAt: new Date("2026-02-19").toISOString(),
  },
  {
    id: "a7", type: "call", subject: "要件ヒアリング",
    description: "現場管理アプリの要件ヒアリング。オフライン対応とGPS機能が必須要件。現場作業員20名が対象ユーザー。",
    customerId: "c7", customerName: "建設コンサルタント株式会社",
    dealId: "d7", dealTitle: "現場管理アプリ開発",
    assignedTo: "u5", scheduledAt: new Date("2026-02-15T11:00:00").toISOString(),
    completedAt: new Date("2026-02-15T12:00:00").toISOString(), completed: true,
    createdAt: new Date("2026-02-15").toISOString(),
  },
  {
    id: "a8", type: "meeting", subject: "WMS刷新 詳細要件確認",
    description: "倉庫管理システムの詳細要件確認MTG。3拠点の倉庫を統合管理する必要あり。RFID導入も検討中。",
    customerId: "c8", customerName: "物流ネットワーク株式会社",
    dealId: "d8", dealTitle: "倉庫管理システム刷新",
    assignedTo: "u3", scheduledAt: new Date("2026-02-26T10:00:00").toISOString(),
    completedAt: new Date("2026-02-26T12:00:00").toISOString(), completed: true,
    createdAt: new Date("2026-02-26").toISOString(),
  },
  {
    id: "a9", type: "email", subject: "初回アプローチメール",
    description: "エナジーテックへの初回コンタクト。会社紹介資料と事例集を添付。アポイント打診。",
    customerId: "c9", customerName: "エナジーテック株式会社",
    assignedTo: "u4", scheduledAt: new Date("2026-02-12T10:00:00").toISOString(),
    completedAt: new Date("2026-02-12T10:00:00").toISOString(), completed: true,
    createdAt: new Date("2026-02-12").toISOString(),
  },
  {
    id: "a10", type: "meeting", subject: "スマート農業 現地視察",
    description: "農場での現地視察を実施。現在の課題を詳しくヒアリング。水分センサーや温度管理の自動化ニーズ確認。",
    customerId: "c11", customerName: "アグリテック株式会社",
    dealId: "d10", dealTitle: "スマート農業管理システム",
    assignedTo: "u4", scheduledAt: new Date("2026-02-21T09:00:00").toISOString(),
    completedAt: new Date("2026-02-21T12:00:00").toISOString(), completed: true,
    createdAt: new Date("2026-02-21").toISOString(),
  },
  {
    id: "a11", type: "call", subject: "健康管理アプリ キックオフ確認",
    description: "受注後のキックオフMTG日程確認。開発チームのアサインも完了。",
    customerId: "c12", customerName: "ウェルネスライフ株式会社",
    dealId: "d11", dealTitle: "健康管理アプリ開発",
    assignedTo: "u5", scheduledAt: new Date("2025-10-05T15:00:00").toISOString(),
    completedAt: new Date("2025-10-05T15:30:00").toISOString(), completed: true,
    createdAt: new Date("2025-10-05").toISOString(),
  },
  {
    id: "a12", type: "task", subject: "金融システム 競合分析レポート作成",
    description: "競合A社・B社との機能・価格比較表を作成し提案資料に組み込む。期限は来週月曜日。",
    customerId: "c2", customerName: "フィナンシャルグループ株式会社",
    dealId: "d2", dealTitle: "金融システムリプレイス",
    assignedTo: "u3", scheduledAt: new Date("2026-03-10T18:00:00").toISOString(),
    completed: false, createdAt: new Date("2026-03-01").toISOString(),
  },
  {
    id: "a13", type: "email", subject: "WMS 最終見積書送付",
    description: "倉庫管理システムの最終見積書を送付。値引き後の金額で提示。今週中に回答をお願い。",
    customerId: "c8", customerName: "物流ネットワーク株式会社",
    dealId: "d8", dealTitle: "倉庫管理システム刷新",
    assignedTo: "u3", scheduledAt: new Date("2026-03-01T14:00:00").toISOString(),
    completedAt: new Date("2026-03-01T14:00:00").toISOString(), completed: true,
    createdAt: new Date("2026-03-01").toISOString(),
  },
  {
    id: "a14", type: "meeting", subject: "データ分析基盤 要件定義MTG",
    description: "収集するデータ項目・分析指標の要件定義。KPIダッシュボードのモックアップを見せる予定。",
    customerId: "c6", customerName: "教育サービス株式会社",
    dealId: "d15", dealTitle: "データ分析基盤構築",
    assignedTo: "u5", scheduledAt: new Date("2026-03-12T14:00:00").toISOString(),
    completed: false, createdAt: new Date("2026-03-01").toISOString(),
  },
  {
    id: "a15", type: "note", subject: "クラウド移行 アーキテクチャ設計レビュー",
    description: "AWS構成図のレビュー完了。マルチAZ構成・コスト最適化の観点で修正提案。先方エンジニアと合意。",
    customerId: "c1", customerName: "株式会社テックソリューション",
    dealId: "d1", dealTitle: "クラウド移行プロジェクト",
    assignedTo: "u3", scheduledAt: new Date("2026-03-02T16:00:00").toISOString(),
    completedAt: new Date("2026-03-02T17:00:00").toISOString(), completed: true,
    createdAt: new Date("2026-03-02").toISOString(),
  },
];